/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#c1c6d7',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#8b90a0',
        'outline-variant': '#414754',
        'surface-tint': '#aec6ff',
        primary: '#aec6ff',
        'on-primary': '#002e6b',
        'primary-container': '#0070f3',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#0059c5',
        secondary: '#a2e7ff',
        'on-secondary': '#003642',
        'secondary-container': '#00d2fd',
        'on-secondary-container': '#005669',
        tertiary: '#7bd0ff',
        'on-tertiary': '#00354a',
        'tertiary-container': '#007fac',
        'on-tertiary-container': '#ffffff',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#aec6ff',
        'on-primary-fixed': '#001a43',
        'on-primary-fixed-variant': '#004397',
        'secondary-fixed': '#b4ebff',
        'secondary-fixed-dim': '#3cd7ff',
        'on-secondary-fixed': '#001f27',
        'on-secondary-fixed-variant': '#004e5f',
        'tertiary-fixed': '#c4e7ff',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-tertiary-fixed': '#001e2c',
        'on-tertiary-fixed-variant': '#004c69',
        background: '#0b1326',
        'on-background': '#dae2fd',
        'surface-variant': '#2d3449',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['4.8rem', { lineHeight: '5.6rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['3.6rem', { lineHeight: '4.4rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['2.4rem', { lineHeight: '3.2rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['2rem', { lineHeight: '2.8rem', fontWeight: '600' }],
        'title-lg': ['1.8rem', { lineHeight: '2.6rem', fontWeight: '600' }],
        'title-md': ['1.6rem', { lineHeight: '2.4rem', fontWeight: '600' }],
        'body-lg': ['1.6rem', { lineHeight: '2.6rem', fontWeight: '400' }],
        'body-md': ['1.4rem', { lineHeight: '2.2rem', fontWeight: '400' }],
        'body-sm': ['1.2rem', { lineHeight: '1.8rem', fontWeight: '400' }],
        'label-lg': ['1.4rem', { lineHeight: '2rem', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['1.2rem', { lineHeight: '1.6rem', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-sm': ['1rem', { lineHeight: '1.4rem', letterSpacing: '0.08em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '2rem',
        'margin-mobile': '1rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
      },
    },
  },
  plugins: [],
};
